config:
  validation: true
  warningsAsErrors: true

complexity:
  LongParameterList:
    ignoreDefaultParameters: true
  TooManyFunctions:
    ignoreAnnotatedFunctions:
      - Preview

naming:
  FunctionNaming:
    ignoreAnnotated:
      - Composable

style:
  MagicNumber:
    ignoreCompanionObjectPropertyDeclaration: true
    ignorePropertyDeclaration: true
    ignoreAnnotated:
      - Composable
  UnusedPrivateFunction:
    ignoreAnnotated:
      - Preview
